name: /dev/lawyer
description: Law, technology, and the space between
url: http://writing.kemitchell.com
permalink: :year/:month/:day/:title.html
author: Kyle Mitchell
homepage: http://kemitchell.com
highlighter: rouge
gems:
- jekyll-sass-converter
- jekyll-feed
